image: debian:latest

before_script:
    - apt-get update -qq && apt-get install -y -qq gnuradio-dev libcppunit-dev cmake swig pkg-config build-essential git libitpp-dev

test:
    script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr ..
        - make
        - make install
        - ldconfig
        - python -c "import ccsds"
