
stages:
        - build
        - test
        - deploy

ccsds_build:debian:
    image: debian:latest
    before_script:
        - apt-get update -qq && apt-get install -y -qq  libcppunit-dev cmake pkg-config build-essential libconfig++-dev valgrind doxygen gnuradio-dev libitpp-dev git swig python python-dev python3 python3-dev
    stage: build
    script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        - make
        - make install
        - ldconfig
        - python -c "import ccsds"
        - cd ..

    artifacts:
        paths:
            - build/

ccsds_test:debian:
    image: debian:latest
    before_script:
        - apt-get update -qq && apt-get install -y -qq  libcppunit-dev cmake pkg-config build-essential libconfig++-dev valgrind doxygen gnuradio-dev libitpp-dev git swig python python-dev python3 python3-dev
    stage: test
    dependencies:
        - ccsds_build:debian
    script:
        - cd build
        - make CTEST_OUTPUT_ON_FAILURE=1 test

ccsds_build:opensuse:
    image: opensuse/leap
    before_script:
        - zypper ref && zypper install -y -l gcc-c++ cppunit-devel cmake pkg-config libconfig++-devel valgrind doxygen patterns-devel-C-C++-devel_C_C++ gnuradio-devel git swig itpp-devel boost-devel libboost_atomic-devel libboost_filesystem-devel libboost_system-devel gcovr python python-devel extra-cmake-modules python3 python3-devel
    stage: build
    script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=1 ..
        - make
        - make install
        - ldconfig
        - python -c "import ccsds"
        - cd ..
    artifacts:
        paths:
            - build/

ccsds_test:opensuse:
    image: opensuse/leap
    before_script:
        - zypper ref && zypper install -y -l gcc-c++ cppunit-devel cmake pkg-config libconfig++-devel valgrind doxygen patterns-devel-C-C++-devel_C_C++ gnuradio-devel git swig itpp-devel boost-devel libboost_atomic-devel libboost_filesystem-devel libboost_system-devel gcovr python python-devel extra-cmake-modules python3 python3-devel glibc-locale
    stage: test
    dependencies:
        - ccsds_build:opensuse
    script:
        - export LANG=en_US.UTF-8
        - export LANGUAGE=en_US:en
        - export LC_ALL=en_US.UTF-8
        - export PYTHONIOENCODING=utf-8
        - cd build
        - make CTEST_OUTPUT_ON_FAILURE=1 test
        - make coverage
    artifacts:
        paths:
            - build/

pages:
    image: opensuse/leap
    stage: deploy
    dependencies:
        - ccsds_test:opensuse
    script:
        - mv build/coverage/ public/
    artifacts:
        paths:
            - public

